apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/rajat-tags-gmal-com/camel-app:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/rajat-tags-gmal-com/camel-app:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: camel-app
        chartPath: charts/camel-app
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/rajat-tags-gmal-com/camel-app"
          image.tag: "{{.TAG}}"
